# Use strong user password
version: '3.1'

services:
  backend:
#    image: IMAGE_LINK
#    build: .
    restart: unless-stopped
    ports:
      - "32504:8000"
    environment:
      SYNC_CATCH_UP: 163000
      MONGO_DB_CONNECTION: mongodb://root:example@mongo:27017/
    volumes:
      - leveldb_data:/data

volumes:
  leveldb_data: